# Dependabot configuration
# Automatically generated by Terraform

version: 2
updates:
%{ for ecosystem in ecosystems ~}
  - package-ecosystem: "${ecosystem.package_ecosystem}"
    directory: "${ecosystem.directory}"
    schedule:
      interval: "${ecosystem.schedule}"  # Monthly for regular updates
      day: "${try(ecosystem.day, "monday")}"
      time: "${try(ecosystem.time, "04:00")}"
      timezone: "America/Los_Angeles"
    
    # Pull request limits
    open-pull-requests-limit: ${open_pull_requests_limit}
    
    # Labels to add to PRs
    labels:
%{ for label in labels ~}
      - "${label}"
%{ endfor ~}
    
    # Assignees (you)
    assignees:
%{ for assignee in assignees ~}
      - "${assignee}"
%{ endfor ~}
    
    # Commit message prefix
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    
    # Priority for security updates
    # Security updates are ALWAYS created immediately regardless of schedule
    
    # Allow dependency updates
    allow:
      - dependency-type: "all"
    
    # Versioning strategy - only increase versions when necessary (security)
    versioning-strategy: increase-if-necessary
    
    # Ignore specific dependencies if needed
    ignore:
      # Example: - dependency-name: "aws-sdk"
      #            versions: ["2.x"]
    
    # Group updates to reduce PR noise
%{ if ecosystem.package_ecosystem == "npm" ~}
    groups:
      production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
%{ endif ~}
    
    # Security updates only (uncomment if you want less noise)
    # versioning-strategy: increase-if-necessary
    
%{ endfor ~}

# Enable security updates
enable-beta-ecosystems: true